const TR_EN_WORDS = {
  Lila: 'Lilac',
  Sari: 'Yellow',
  'Sarı': 'Yellow',
  Pembe: 'Pink',
  Mavi: 'Blue',
  Yesil: 'Green',
  'Yeşil': 'Green',
  Kirmizi: 'Red',
  'Kırmızı': 'Red',
  Siyah: 'Black',
  Beyaz: 'White',
  Gri: 'Grey',
  Mor: 'Purple',
  Bej: 'Beige',
  Kahverengi: 'Brown',
  Lacivert: 'Navy',
  Bordo: 'Burgundy',
  Turkuaz: 'Turquoise',
  Haki: 'Khaki',
  Hardal: 'Mustard',
  Krem: 'Cream',
  Somon: 'Salmon',
  Pudra: 'Powder',
  Ekru: 'Ecru',
  Altin: 'Gold',
  'Altın': 'Gold',
  Gumus: 'Silver',
  'Gümüş': 'Silver',
  Taba: 'Tan',
  Antrasit: 'Charcoal',
  Gok: 'Sky',
  'Gök': 'Sky',
  Buz: 'Ice',
  Acik: 'Light',
  'Açık': 'Light',
  Koyu: 'Dark',
  Gece: 'Night',
  Nane: 'Mint',
  Zeytin: 'Olive',
  Zumrut: 'Emerald',
  'Zümrüt': 'Emerald',
  Gul: 'Rose',
  'Gül': 'Rose',
  Kurusu: 'Dry',
  Visne: 'Cherry',
  'Vişne': 'Cherry',
  Kiremit: 'Terracotta',
  Mercan: 'Coral',
  Bluz: 'Blouse',
  Elbise: 'Dress',
  Etek: 'Skirt',
  Pantolon: 'Trousers',
  Gomlek: 'Shirt',
  'Gömlek': 'Shirt',
  Kazak: 'Sweater',
  Ceket: 'Jacket',
  Hirka: 'Cardigan',
  'Hırka': 'Cardigan',
  Mont: 'Coat',
  Kaban: 'Overcoat',
  Palto: 'Coat',
  Yelek: 'Vest',
  Body: 'Bodysuit',
  Crop: 'Crop',
  Tunik: 'Tunic',
  Tulum: 'Jumpsuit',
  Jile: 'Pinafore',
  Atlet: 'Tank Top',
  Triko: 'Knit',
  Tisort: 'T-Shirt',
  'Tişört': 'T-Shirt',
  'T-Shirt': 'T-Shirt',
  Tayt: 'Leggings',
  Sort: 'Shorts',
  'Şort': 'Shorts',
  Korse: 'Corset',
  Top: 'Top',
  'Svitşört': 'Sweatshirt',
  Sweatshirt: 'Sweatshirt',
  Wideleg: 'Wide-Leg',
  Bustiyer: 'Bustier',
  Trenckot: 'Trench Coat',
  'Trençkot': 'Trench Coat',
  Blazer: 'Blazer',
  Bomber: 'Bomber',
  Ayakkabi: 'Shoes',
  Ayakkabı: 'Shoes',
  Bot: 'Boots',
  Cizme: 'Boots',
  'Çizme': 'Boots',
  Sandalet: 'Sandals',
  Sneaker: 'Sneakers',
  Terlik: 'Slippers',
  Topuklu: 'Heels',
  Babet: 'Flats',
  Loafer: 'Loafers',
  Stiletto: 'Stilettos',
  Platform: 'Platform',
  Canta: 'Bag',
  'Çanta': 'Bag',
  Saat: 'Watch',
  Kemer: 'Belt',
  Gozluk: 'Sunglasses',
  'Gözlük': 'Sunglasses',
  Kolye: 'Necklace',
  Kupe: 'Earrings',
  'Küpe': 'Earrings',
  Yuzuk: 'Ring',
  'Yüzük': 'Ring',
  Bileklik: 'Bracelet',
  Cuzdan: 'Wallet',
  'Cüzdan': 'Wallet',
  Sapka: 'Hat',
  'Şapka': 'Hat',
  Saten: 'Satin',
  Sifon: 'Chiffon',
  'Şifon': 'Chiffon',
  Dantel: 'Lace',
  Keten: 'Linen',
  Denim: 'Denim',
  Kadife: 'Velvet',
  Organza: 'Organza',
  Orgu: 'Knit',
  'Örgü': 'Knit',
  Deri: 'Leather',
  Suni: 'Faux',
  Overlok: 'Overlock',
  Baski: 'Print',
  'Baskı': 'Print',
  Dokuma: 'Woven',
  Ipek: 'Silk',
  'İpek': 'Silk',
  Suet: 'Suede',
  'Süet': 'Suede',
  Yun: 'Wool',
  'Yün': 'Wool',
  Detayli: 'Detail',
  'Detaylı': 'Detail',
  Tas: 'Stone',
  'Taş': 'Stone',
  Basic: 'Basic',
  Modern: 'Modern',
  Klasik: 'Classic',
  Mini: 'Mini',
  Maxi: 'Maxi',
  Midi: 'Midi',
  Oversize: 'Oversize',
  Slim: 'Slim',
  Fit: 'Fit',
  Zincirli: 'Chain',
  Omuz: 'Shoulder',
  El: 'Hand',
  Yuksek: 'High',
  'Yüksek': 'High',
  Bel: 'Waist',
  Bol: 'Wide',
  Paca: 'Leg',
  'Paça': 'Leg',
  Dar: 'Slim',
  Uzun: 'Long',
  Kisa: 'Short',
  'Kısa': 'Short',
  Kesim: 'Cut',
  Yaka: 'Neck',
  Balikci: 'Turtleneck',
  'Balıkçı': 'Turtleneck',
  Askili: 'Strapped',
  'Askılı': 'Strapped',
  Drapeli: 'Draped',
  Zarif: 'Elegant',
  Sik: 'Chic',
  'Şık': 'Chic',
  Minimal: 'Minimal',
  Tasarim: 'Design',
  'Tasarım': 'Design',
  Sade: 'Simple',
  Gunluk: 'Casual',
  'Günlük': 'Casual',
  Casual: 'Casual',
  Spor: 'Sporty',
  Bohem: 'Bohemian',
  Jean: 'Denim',
  Kot: 'Denim',
  Mom: 'Mom',
  Kargo: 'Cargo',
  Plazzo: 'Palazzo',
  Jeans: 'Jeans',
  Desenli: 'Patterned',
  Kapusonlu: 'Hooded',
  'Kapüşonlu': 'Hooded',
  Cicekli: 'Floral',
  'Çiçekli': 'Floral',
  Kolsuz: 'Sleeveless',
  Tek: 'One',
  Kumas: 'Tailored',
  'Kumaş': 'Tailored',
  Yazlik: 'Summer',
  'Yazlık': 'Summer',
  Ust: 'Top',
  'Üst': 'Top',
  Giyim: 'Wear',
  Alt: 'Bottom',
  Dis: 'Outer',
  'Dış': 'Outer',
  'Dış Giyim': 'Outerwear',
  'Üst Giyim': 'Tops',
  'Alt Giyim': 'Bottoms',
  'Askılı Elbise': 'Slip Dress',
  'Midi Elbise': 'Midi Dress',
  'Mini Elbise': 'Mini Dress',
  'Crop Tişört': 'Crop T-Shirt',
  'Crop Kazak': 'Crop Sweater',
  'Jean Pantolon': 'Jeans',
  'Mom Jean': 'Mom Jeans',
  'Kargo Pantolon': 'Cargo Pants',
  'Mini Etek': 'Mini Skirt',
  'Uzun Etek': 'Maxi Skirt',
  'Kot Etek': 'Denim Skirt',
  'Deri Ceket': 'Leather Jacket',
  'Blazer Ceket': 'Blazer Jacket',
  'Bomber Ceket': 'Bomber Jacket',
  'Spor Ayakkabı': 'Sneakers',
  'Açık Mavi': 'Light Blue',
  'Gök Mavisi': 'Sky Blue',
  'Gece Mavisi': 'Midnight Blue',
  'Buz Mavisi': 'Ice Blue',
  'Hardal Sarısı': 'Mustard Yellow',
  'Pudra Pembesi': 'Powder Pink',
  'Gül Kurusu': 'Dusty Rose',
  'Zümrüt Yeşili': 'Emerald Green',
  'Nane Yeşili': 'Mint Green',
  'Haki Yeşili': 'Olive Green',
  'Orman Yeşili': 'Forest Green',
  'Zeytin Yeşili': 'Olive',
  'Gece Siyahı': 'Jet Black',
  'Su Yeşili': 'Aqua',
  'Yüksek Bel': 'High Waist',
  'Bol Paça': 'Wide Leg',
  'Dar Kesim': 'Slim Fit',
  'Balıkçı Yaka': 'Turtleneck',
};

const COLOR_MAP_EN = {
  Lila: 'Lilac',
  Sari: 'Yellow',
  'Sarı': 'Yellow',
  Pembe: 'Pink',
  Mavi: 'Blue',
  Yesil: 'Green',
  'Yeşil': 'Green',
  Kirmizi: 'Red',
  'Kırmızı': 'Red',
  Siyah: 'Black',
  Beyaz: 'White',
  Gri: 'Grey',
  Mor: 'Purple',
  Bej: 'Beige',
  Kahverengi: 'Brown',
  Lacivert: 'Navy',
  Bordo: 'Burgundy',
  Turkuaz: 'Turquoise',
  Haki: 'Khaki',
  Hardal: 'Mustard',
  Krem: 'Cream',
  Somon: 'Salmon',
  Pudra: 'Powder Pink',
  Ekru: 'Ecru',
  Altin: 'Gold',
  'Altın': 'Gold',
  Gumus: 'Silver',
  'Gümüş': 'Silver',
  Taba: 'Tan',
  Antrasit: 'Charcoal',
  'Açık Mavi': 'Light Blue',
  'Gök Mavisi': 'Sky Blue',
  'Gece Mavisi': 'Navy Blue',
  'Buz Mavisi': 'Ice Blue',
  'Hardal Sarısı': 'Mustard Yellow',
  'Pudra Pembesi': 'Powder Pink',
  'Gül Kurusu': 'Rose',
  'Zümrüt Yeşili': 'Emerald Green',
  'Nane Yeşili': 'Mint Green',
  'Zeytin Yeşili': 'Olive',
  'Haki Yeşili': 'Olive Green',
  'Orman Yeşili': 'Forest Green',
  Mercan: 'Coral',
  'Vişne': 'Cherry',
  Visne: 'Cherry',
  Kiremit: 'Terracotta',
  'Su Yeşili': 'Aqua',
  'Gok Mavisi': 'Sky Blue',
  'Gece Siyahı': 'Jet Black',
};

const resolveLang = (langOrI18n) => {
  if (!langOrI18n) {
    return 'tr';
  }

  if (typeof langOrI18n === 'string') {
    return langOrI18n.split('-')[0];
  }

  if (typeof langOrI18n === 'object' && typeof langOrI18n.language === 'string') {
    return langOrI18n.language.split('-')[0];
  }

  return 'tr';
};

const translateProductName = (name) => {
  if (!name) {
    return name;
  }

  const words = name.trim().split(/\s+/);
  const result = [];
  let index = 0;

  while (index < words.length) {
    if (index + 1 < words.length) {
      const combined = `${words[index]} ${words[index + 1]}`;

      if (TR_EN_WORDS[combined]) {
        result.push(TR_EN_WORDS[combined]);
        index += 2;
        continue;
      }
    }

    result.push(TR_EN_WORDS[words[index]] || words[index]);
    index += 1;
  }

  return result.join(' ');
};

export const translateColor = (color, langOrI18n) => {
  const lang = resolveLang(langOrI18n);

  if (!color || lang === 'tr') {
    return color;
  }

  return COLOR_MAP_EN[color] || color;
};

export const translateName = (name, langOrI18n) => {
  const lang = resolveLang(langOrI18n);

  if (!name || lang === 'tr') {
    return name;
  }

  return translateProductName(name);
};
